version: "3.7"

services:
  backend:
    container_name: back
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    tty: true
    volumes:
      - type: bind
        source: ./backend
        target: /api
    depends_on:
      - db
    ports:
      - "3000:3000"

  frontend:
    container_name: front
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    tty: true
    volumes:
      - type: bind
        source: ./frontend
        target: /app
    ports:
      - "3333:3333"

  db:
    image: postgres:14
    container_name: postgres
    ports:
      - 5432:5432
    volumes:
      - db-store:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
volumes:
  db-store:
