version: "3.7"

services:
  backend:
    container_name: back
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    tty: true
    volumes:
      - type: bind
        source: ./backend
        target: /api
    ports:
      - "3000:3000"

  frontend:
    container_name: front
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    tty: true
    volumes:
      - type: bind
        source: ./frontend
        target: /app
    ports:
      - "3333:3333"
